import type { Metadata } from 'next';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const layout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <div className="w-full grid  h-screen grid-cols-1 tablet:grid-cols-[457px,1fr]">
    <div className="w-full h-screen bg-black tablet:flex hidden">
      <Image
        src="/authSideImage.png"
        alt="logo"
        width={662}
        height={600}
        className="h-full w-full object-cover "
      />
    </div>
    <div className="overflow-x-hidden overflow-y-auto w-full grid tablet:grid-rows-1 grid-rows-[60px,1fr]">
      <div className="w-full bg-gray-500 tablet:hidden flex">
        {/* Header Display in mobile view  */}
      </div>
      <div className="flex items-start justify-center py-10">
        <div className="w-full min-h-full max-w-[500px] flex items-center justify-center p-5">
          {children}{' '}
        </div>
      </div>
    </div>
  </div>
);

export default layout;
