import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { StoreProvider } from '@/redux/slices';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const layout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <StoreProvider>
    <html lang="en">
      <body className={`${nunito.className} text-text`}>{children}</body>
    </html>
  </StoreProvider>
);

export default layout;
